//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woof.ServiceEx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Woof.ServiceEx.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting event log &quot;{0}&quot;....
        /// </summary>
        public static string DeletingEventLog {
            get {
                return ResourceManager.GetString("DeletingEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting event source &quot;{0}&quot;....
        /// </summary>
        public static string DeletingEventSource {
            get {
                return ResourceManager.GetString("DeletingEventSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE..
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event source {0} already exists in {1} log! Unregistering....
        /// </summary>
        public static string EventSourceExists {
            get {
                return ResourceManager.GetString("EventSourceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing service....
        /// </summary>
        public static string InitializingService {
            get {
                return ResourceManager.GetString("InitializingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///NAME
        ///    {0}
        ///
        ///DESCRIPTION
        ///    {1}
        ///
        ///USAGE
        ///    Service installation:
        ///        .\{2} -i
        ///
        ///    Service uninstallation:
        ///        .\{2} -u [-s=&lt;string&gt;] [-e=&lt;string&gt;] [l=&lt;string&gt;]
        ///            -s=service_name : removes service with specified name identifier
        ///            -e=event_source : removes specified event source
        ///            -l=event_log: removes specified event log
        ///
        ///    Test run:
        ///        .\{2} -t
        ///
        ///EXAMPLES
        ///    .\{2} -i
        ///    .\{2} -u
        ///    .\{2} -u -l=&quot;My Application Log&quot;
        ///.
        /// </summary>
        public static string InstallerHelp {
            get {
                return ResourceManager.GetString("InstallerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service display name (assembly title) must be different from the product name (assembly product)
        ///in order to install the service..
        /// </summary>
        public static string InvalidEventSourceName {
            get {
                return ResourceManager.GetString("InvalidEventSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid interval format.
        /// </summary>
        public static string InvalidIntervalFormat {
            get {
                return ResourceManager.GetString("InvalidIntervalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event log &quot;{0}&quot; doesn&apos;t exist..
        /// </summary>
        public static string NoEventLog {
            get {
                return ResourceManager.GetString("NoEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event source &quot;{0}&quot; doesn&apos;t exist..
        /// </summary>
        public static string NoEventSource {
            get {
                return ResourceManager.GetString("NoEventSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK..
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ENTER to continue....
        /// </summary>
        public static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System restart is required in order to delete the event source for this uninstalled service..
        /// </summary>
        public static string RestartAdvised {
            get {
                return ResourceManager.GetString("RestartAdvised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System restart is required in order to install the service..
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelfTest completed..
        /// </summary>
        public static string SelfTestCompleted {
            get {
                return ResourceManager.GetString("SelfTestCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
    }
}
